import 'dart:ui';
const BGroundStartPage = Color(0xFFFEF9F5);
const BtnStartPage = Color(0xFF6EB3CF);
const titleStartPage = Color(0xFF730F71);
const titleStartPage2 = Color(0xFF4D4D4D);
const BGroundCardHomePage = Color(0xFF77543E);
const BGroundCategoryHomePage = Color(0xFFFAE2FA);
const BGroundCategoryHomePageMen = Color(0xFFe6e6e6);
const BGroundCategoryHomePageMen2 = Color(0xFF8F8F8F);
const BGroundTextColor = Color(0xFFC954C7);
const BGroundTextColorMen = Color(0xFF666666);
const BGroundTextFilledColor = Color(0xFFFAD7F8);
const BGroundTextFilledColorMen = Color(0xFFB7B7B7);
const BGroundTitleColor = Color(0xFFCF4FCD);
const BGroundContainerCheck = Color(0xFFFE7E00);
const kColorButtom = Color(0xFFf4f1f2);
const kSearchFiledColor = Color(0xFFEFEFEF);
const kSelectTabColor = Color(0xFF141321);
const kUnSelectTabColor = Color(0xFFC4C4C4);

