import 'dart:ui';
const BGroundStartPage = Color(0xFFFEF9F5);
const BtnStartPage = Color(0xFF6EB3CF);
const titleStartPage = Color(0xFF921F47);
const titleStartPage2 = Color(0xFF41526e);
const BGroundCardHomePage = Color(0xFF77543E);
const BGroundCategoryHomePage = Color(0xFFf3e0da);
const BGroundCategoryHomePageMen = Color(0xFFd3dceb);
const BGroundCategoryHomePageMen2 = Color(0xFF8F8F8F);
const BGroundTextColor = Color(0xFFC954C7);
const BGroundTextColorMen = Color(0xFF666666);
const BGroundTextFilledColor = Color(0xFFFAD7F8);
const BGroundTextFilledColorMen = Color(0xFFB7B7B7);
const BGroundTitleColor = Color(0xFFCF4FCD);
const BGroundTitleColorMen = Color(0xFF003399);
const BGroundContainerCheck = Color(0xFFFE7E00);
const kColorButtom = Color(0xFFf4f1f2);
const kSearchFiledColor = Color(0xFFEFEFEF);
const kSelectTabColor = Color(0xFF141321);
const kUnSelectTabColor = Color(0xFFC4C4C4);
const textTitleMyReservation = Color(0xFF606062);
const BGContainerMyReservation = Color(0xFF465B6C);
const BGDate = Color(0xFFf3e0da);
const BGDateMen = Color(0xFFd3dceb);
const BGTextDate = Color(0xFF921F47);
const BGTextDateMen = Color(0xFF41526e);
const BGTextFiledWomen = Color(0xFFFAF2F0);

